# Generated by Django 3.1.2 on 2020-11-19 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
