# Generated by Django 3.1.2 on 2020-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
