# Generated by Django 3.1.2 on 2020-12-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201129_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Shortdesc',
            field=models.TextField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
