# Generated by Django 3.1.2 on 2020-12-02 15:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_project_shortdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Shortdesc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
