# Generated by Django 3.1.2 on 2020-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Date', models.DateField()),
                ('Description', models.CharField(max_length=100)),
                ('Post', models.TextField()),
            ],
        ),
    ]
