# Generated by Django 3.1.2 on 2020-11-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
