# Generated by Django 3.1.2 on 2020-11-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
