# Generated by Django 3.1.2 on 2020-12-03 07:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201202_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Description',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
    ]
